Library Project  (JavaScript Section)
ClintonEnyinna/library pull request #1
Opened 2020-04-22 22:50 UTC by ClintonEnyinna

We implemented the following features: 

- A user can add a new book to the library
- He/She can delete one or many books
- Can update the read status

2020-04-23 02:41 UTC, bellom requested changes
## Hi Team  :clap: 

**Kindly check out my comments below;**

According to the Odin instructions, we need to add `remove button` on each book
![image](https://user-images.githubusercontent.com/31897434/80052322-4d3d7400-8512-11ea-8b3c-42a6704c7485.png)

According to the Odin instructions, we need to add `toggle button` on each book
![image](https://user-images.githubusercontent.com/31897434/80052332-575f7280-8512-11ea-9567-e261d33afb59.png)

![image](https://user-images.githubusercontent.com/31897434/80053116-0fd9e600-8514-11ea-84fa-e8599a9a0aee.png)

It would be nice to add little styling, as you know this project would be added to your portfolio 👍 

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-04-23 11:19 UTC, bafiam commented
Hey, Thanks for the feedback.
- Styling has been implemented

> **For the button, we improved the project by adding additional functionality. We used a checkbox which is more like a button in our case making the library more dynamic in that a user is able to delete a single selected entry as well able to delete more than one selected entry. In addition, we reused the same checkbox, to allow the user to toggle back and forth between a read status of "yes and no "; try it out. Also as an additional feature, user is able to toggle back and forth with more that one entry u know in the case of big data sets**. 

Thank you.

2020-04-23 23:31 UTC, shloch requested changes
## hello @ClintonEnyinna , @bafiam 

Nice job guys, It all works out fine........and properly

### [optional changes]

- Apply some controls to make sure that `pages` entered is always a number
![Screen Shot 2020-04-24 at 12 13 50 AM](https://user-images.githubusercontent.com/40712459/80158250-f3938300-85bf-11ea-855c-99a8294b8a63.png)
(This is not specified in requirements, but will be good to have)

### [required changes]
See observations below :

2020-04-23 23:31 UTC, shloch commented on js/main.js
> +});
There's a good reason on using JAVASCRIPT, one of them is to not reload page necessarily. Ideally you should call the `render()` function after deleting data (Figure out a way to make that work)

### no reloads

2020-04-23 23:31 UTC, shloch commented on js/main.js
> +});
Ideally you should call the `render()` function after EDITING data (Figure out a way to make that work)

2020-04-23 23:31 UTC, shloch commented on js/main.js
> +    }
From the requirements, you had to put the `DELETE` button BESIDE each book.
Also, still from requirements, there's this javascript `data-attribute` (from a table display), that  gives you the `INDEX` of a book. This your algorithm does a search on all books to determine which one is checked. If there're 1000 books, for every delete, you run a search, this is very inefficient. On top of that you have a page reload.

([read about Data-attributes here](https://css-tricks.com/a-complete-guide-to-data-attributes/))
Inside your `render()` function when looping through books to generate them on a table, you add a delete button beside each book and pass `rowIndex` to that delete function (you get the idea)
 [[see requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/remove_requirement.png)]

2020-04-23 23:31 UTC, shloch commented on js/main.js
> +  const temp = myLibrary.filter((i) => i);
Check my explanation below, regarding this search approach..it's inefficient

2020-04-24 18:05 UTC, jofer86 approved these changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- Great job at addressing the required changes, with the implementations that you did the app runs more efficiently as you are leveraging the correct properties to do the required actions. Great job!!!
# `status: approved` :+1: :rocket: :+1: 
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-04-24 19:07 UTC, merged